#!/bin/bash
# scripts
# vim: ft=sh

#   __|    \    _ \  |      _ \   __| __ __| __ __|
#  (      _ \     /  |     (   | (_ |    |      |
# \___| _/  _\ _|_\ ____| \___/ \___|   _|     _|

# --------------------------------------
# Description: carlogtt personal scripts
# --------------------------------------

# -----------------------------------
# path utils
# append or prepend directory to path
# -----------------------------------
append_path() {
    if [[ -n "${1}" && -d "${1}" && ! "${PATH}" == *"${1}"* ]]; then
        export PATH="${PATH:+${PATH}:}${1}"
    fi
}

prepend_path() {
    if [[ -n "${1}" && -d "${1}" && ! "${PATH}" == *"${1}"* ]]; then
        export PATH="${1}${PATH:+:${PATH}}"
    fi
}

# -------------------------------------
# pstree
# Recursively find all process children
# -------------------------------------
pstree() {
    _find_children() {
        for child in $(sudo ps -e -o "pid,ppid" | awk -v ppid="${1}" '$2 == ppid {print $1}'); do
            echo -e '\033[47m'
            sudo ps -p "${child}" -o "pid,ppid,stat,uid,user,pri,ni,tty,%cpu,%mem,rss,vsz,start,time,command"
            echo -e '\033[0m'

            echo -e -n '\033[36m'
            if [[ $(uname -s) == "Darwin" ]]; then
                echo -e "PID Environment Variables\n $(sudo ps eww -o command ${child} | tr ' ' '\n' | awk '/=/{print}' | tr '\n' ' ')"
            else
                echo -e "PID Environment Variables\n $(sudo /bin/cat /proc/${child}/environ | tr '\0' '\n' | grep -E -v '^0$' | tr '\n' ' ')"
            fi

            echo -e -n '\033[32m'
            sudo lsof -p "${child}" | grep -v -E 'IPv4|IPv6'

            echo -e -n '\033[35m'
            sudo lsof -i -a -p "${child}"
            echo -e -n '\033[0m'

            _find_children "${child}"
        done
        echo -e ""
    }

    _find_parents() {
        local child_pid="${1}"
        local parent_pid=$(sudo ps -p "${child_pid}" -o ppid= | tr -d ' ')
        local parents=()

        # Collect all parent PIDs in a list
        while [ "${parent_pid}" -ne 1 ]; do
            parents+=("${parent_pid}")
            child_pid="${parent_pid}"
            parent_pid=$(sudo ps -p "${child_pid}" -o ppid= | tr -d ' ')
        done
        parents+=("1")

        # Print all parent PIDs in reverse order
        for ((idx = ${#parents[@]} - 1; idx >= 0; idx--)); do
            pid="${parents[@]:${idx}:1}"

            echo -e '\033[47m'
            sudo ps -p "${pid}" -o "pid,ppid,stat,uid,user,pri,ni,tty,%cpu,%mem,rss,vsz,start,time,command"
            echo -e '\033[0m'

            echo -e -n '\033[36m'
            if [[ $(uname -s) == "Darwin" ]]; then
                echo -e "PID Environment Variables\n $(sudo ps eww -o command ${pid} | tr ' ' '\n' | awk '/=/{print}' | tr '\n' ' ')"
            else
                echo -e "PID Environment Variables\n $(sudo /bin/cat /proc/${pid}/environ | tr '\0' '\n' | grep -E -v '^0$' | tr '\n' ' ')"
            fi

            echo -e -n '\033[32m'
            sudo lsof -p "${pid}" | grep -v -E 'IPv4|IPv6'

            echo -e -n '\033[35m'
            sudo lsof -i -a -p "${pid}"
            echo -e -n '\033[0m'
        done
        echo -e ""
    }

    # ENTRY POINT
    if [[ -z "${1}" ]]; then
        echo -e "Usage: pstree <PID>"
        return 1
    fi

    if ! sudo ps -p "${1}" >/dev/null 2>&1; then
        echo -e "Invalid <PID>"
        return 1
    fi

    # Print parent processes
    _find_parents "${1}" | awk 'NF || !blank++'

    # Print target process
    echo -e '\033[43m'
    sudo ps -p "${1}" -o "pid,ppid,stat,uid,user,pri,ni,tty,%cpu,%mem,rss,vsz,start,time,command"
    echo -e '\033[0m'

    echo -e -n '\033[36m'
    if [[ $(uname -s) == "Darwin" ]]; then
        echo -e "PID Environment Variables\n $(sudo ps eww -o command ${1} | tr ' ' '\n' | awk '/=/{print}' | tr '\n' ' ')"
    else
        echo -e "PID Environment Variables\n $(sudo /bin/cat /proc/${1}/environ | tr '\0' '\n' | grep -E -v '^0$' | tr '\n' ' ')"
    fi

    echo -e -n '\033[32m'
    sudo lsof -p "${1}" | grep -v -E 'IPv4|IPv6'

    echo -e -n '\033[35m'
    sudo lsof -i -a -p "${1}"
    echo  -e -n '\033[0m'

    echo -e ""

    # Print child processes
    _find_children "${1}" | awk 'NF || !blank++'
}

# --------------------------------------
# mkextract
# Extract files in their own directories
# --------------------------------------
mkextract() {
    _extract() {
        case $1 in
            *.tar)                        tar -xf          "${1}"              ;;

            *.tar.gz | *.tgz)             tar --gzip -xf   "${1}"              ;;
            *.tar.bz2 | *.tbz2 | *.tbz)   tar --bzip2 -xf  "${1}"              ;;
            *.tar.xz | *.txz)             tar --xz -xf     "${1}"              ;;
            *.tar.lz)                     tar --lzip -xf   "${1}"              ;;
            *.tar.lzma | *.tlz)           tar --lzma -xf   "${1}"              ;;
            *.tar.lzo)                    tar --lzop -xf   "${1}"              ;;
            *.tar.zst | *.tzst)           tar --zstd -xf   "${1}"              ;;
            *.tar.Z)                      tar -Z -xf       "${1}"              ;;

            *.gz)                         gzip -dk         "${1}"              ;;
            *.bz2)                        bzip2 -dk        "${1}"              ;;
            *.xz | *.lzma)                xz -dk           "${1}"              ;;
            *.zst)                        zstd -dk         "${1}"              ;;
            *.Z)                          uncompress       "${1}"              ;;

            *.zip)                        unzip            "${1}"              ;;
            *.7z)                         7z x             "${1}"              ;;
            *.rar)                        7z x             "${1}"              ;;
            *.iso)                        7z x             "${1}"              ;;
            *)                            echo "'${1}' cannot be extracted" ;;
        esac
    }

    # ENTRY POINT
    if [[ -z "${1}" ]]; then
        echo -e "Usage: mkextract <FILE(s)>"
        return 1
    fi

    for file in "$@"; do
        local basename=$(basename "${file}")
        local ext_dir_name="${basename%%\.*}"
        local dirpath=$(realpath -- "$(dirname "${file}")")
        local filepath=$(realpath -- "${file}")

        if [ -f "${filepath}" ]; then
            mkdir -p -- "${dirpath}/${ext_dir_name}/extract"
            mv -- "${filepath}" "${dirpath}/${ext_dir_name}"
            cp -- "${dirpath}/${ext_dir_name}/${file}" "${dirpath}/${ext_dir_name}/extract/${file}"
            pushd "${dirpath}/${ext_dir_name}/extract/" >/dev/null 2>&1 || exit 1
            _extract "${dirpath}/${ext_dir_name}/extract/${file}"
            popd >/dev/null 2>&1 || exit 1
            rm -rf -- "${dirpath}/${ext_dir_name}/extract/${file}"
        else
            echo "'$1' is not a valid file"
        fi
    done
}

# -----------
# mwcurl
# Midway Curl
# -----------
mwcurl() {
    local mw_cookie_file="${HOME}/.midway/cookie"
    curl "$@" --location --cookie "${mw_cookie_file}" --cookie-jar "${mw_cookie_file}"
}

# -----------------
# lptar
# LPT Auto Response
# -----------------
lptar() {
    # Check if 'expect' is installed
    if ! which expect &>/dev/null; then
        echo -e "\033[31m[ERROR] expect not found in PATH\033[0m"
        return 0
    fi

    # Check an arg in passed in
    if [[ -z "$*" ]]; then
        lpt
    fi

    # Execute the expect script logic
    expect <<EOF
eval spawn lpt "$@"
while { true } {
    expect {
        "> (R, p, q)" { send "r\r"; exp_continue }
        "> (y, N, q)" { send "y\r" ; exp_continue }
        eof { exit }
    }
}
EOF
}

# -------------------------------
# reginfo
# Use RIP CLI to get regiion info
# -------------------------------
reginfo() {
    if [[ -z "$1" ]]; then
        echo -e "\033[31m[ERROR] region name must be passed as parameter\033[0m"
        return 0
    fi

    region="$1"

    attributes=(
        accessibility_attributes
        airport_code
        alternate_names
        arn_partition
        availability_zones
        backbone
        backend_vip_zone
        billing_prefix
        bvpc_location
        cluster
        cluster_long_name
        code_name
        custom_properties
        customer_resources_domain_dualstack
        description
        domain
        domain_dualstack
        estimated_launch_date
        external_name
        geolocation_data
        group
        group_long_name
        infra_frontend_vip_zone
        localized_region_name
        long_name
        prod_host_types
        public_dns_suffix
        region_name
        register_date
        service_with_fallback
        services
        standard_frontend_vip_zone
        status
        status_dates
        substrate_dns_suffix
        tags
        timezone_id
        usage_type_prefix
        vpc_dns_domain_suffix
        website_domain
        website_domain_dualstack
    )

    # Declare an associative array
    declare -A output

    # Loop through the array
    for attribute in "${attributes[@]}"; do
        response=$(ripcli -r "${region}" -a "${attribute}" | sed "s/\"/'/g")
        output["${attribute}"]="${response}"
    done

    # Build JSON from the associative array
    json_output="{"
    for key in "${!output[@]}"; do
        json_output+="\"${key}\":\"${output[${key}]}\","
    done

    # Remove trailing comma and close JSON object
    json_output="${json_output%,}}"

    # Replace new lines with ', '
    json_output=$(echo "$json_output" | sed ':a;N;$!ba;s/\n/, /g')

    echo "${json_output}"
}
